# Generated by Django 4.2.5 on 2023-09-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeupapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeupapi.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeupapi.profile')),
            ],
        ),
    ]
